# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a43727cf7b4030518fcdc6d78024804c553b8d59642f87d6ae1a29543b99e1917966e6209187c4e0fd6b78ef56f5f6c0c36b07b6c33db28fa97524060700040c

test:
  secret_key_base: 40a5bc0ad800c1ad7612211950825a2e02440a879080afe6d0806e204c7df310f3dea6e35a1fb78f81b3ca56255d20591e450fe7fdb8d943bc689be1723d633e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
